### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by personasio** [PSeitz/yamaha-nodejs#13]
I cloned to my local machine.  Just try to run the test.js by typing 
`node test.js`

Got the following errors:
simpleCommands.js:14
    return this.getOrDiscoverIP().then(ip => {
                                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/andysio/workspace/test/yamaha.js:1:84)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Now, I have tried to install from npm `npm install yamaha-nodejs`.  Run the test and it worked fine.  What's the difference with the files comparing to one in npm?

**Comment by PSeitz** [comment]
Your nodejs version is probably too old for the latest changes in the file. Any recent version should work fine

**Comment by personasio** [comment]
Yea. you are right. My node doesn't like the ES6 version.  After updating it, it's fine now.  Thanks.
