### ISSUE TITLE
What does that mean?

### ISSUE THREAD

**Issue by LucaGerlich** [PSeitz/yamaha-nodejs#35]
Fatal TypeError: Cannot set property 'getVolume' of null
    at enrichBasicStatus (D:\Coding\YamahaContoller\src\simpleCommands.js:359:27)
    at D:\Coding\YamahaContoller\src\simpleCommands.js:350:16
    at tryCatcher (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:547:31)    
    at Promise._settlePromise (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:489:14)
    at Promise._settlePromiseFromHandler (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:559:17)    
    at Promise._settlePromise (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._fulfillPromises (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:704:14)
    at Promise._settlePromises (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:730:18)
    at Promise._fulfill (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (D:\Coding\YamahaContoller\node_modules\bluebird\js\release\promise.js:559:17)

**Comment by PSeitz** [comment]
When retrieving the volume, a call is made to the receiver to get it as part of the Basic_Status information
```
<YAMAHA_AV cmd="GET"><' + getZone(zone) + '><Basic_Status>GetParam</Basic_Status></' + getZone(zone) + '></YAMAHA_AV>
```
It seems your device doesn't return any information here, what device do you use?

**Comment by LucaGerlich** [comment]
I have the Yamaha RX-V475
